germ_census_list:
    path:     /censuses_{page}.{_format}
    defaults:
        _controller: GermBundle:Census:list
        _format: html
        page: 1
    requirements:
        _format:  html|csv

germ_census_filter:
    path:     /filter/{page}/{filters}
    defaults:
        _format: html
        _controller: GermBundle:Census:list
        page: 1
    requirements:
        filters: ".*"

germ_census_edit:
    path:     /edit/{censusId}
    defaults: { _controller: GermBundle:Census:edit }

germ_census_remove:
    path:     /remove/{censusId}
    defaults: { _controller: GermBundle:Census:remove }

germ_census_create:
    path:     /create
    defaults: { _controller: GermBundle:Census:create }
