<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace Germ\Model\Germ\PersonSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * PersonChurch
 *
 * Structure class for relation person.person_church.
 *
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class PersonChurch extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('person.person_church')
            ->setPrimaryKey([])
            ->addField('person_id', 'uuid')
            ->addField('church_id', 'uuid')
            ;
    }
}
