germ_homepage:
    path:     /
    defaults: { _controller: GermBundle:Main:index }

fos_user:
    prefix:   /access
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

germ_person_list:
    path:     /person/list
    defaults: { _controller: GermBundle:Person:list }

germ_person_edit:
    path:     /person/edit/{personId}
    defaults: { _controller: GermBundle:Person:edit }

germ_person_create:
    path:     /person/create
    defaults: { _controller: GermBundle:Person:create }
