germ_homepage:
    path:     /
    defaults: { _controller: GermBundle:Main:index }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}/access
    defaults:
        _locale: fr
    requirements:
        _locale: fr|en|de

germ_church:
    resource: "@GermBundle/Resources/config/routing/church.yml"
    prefix:   /{_locale}/church
    defaults:
        _locale: fr
    requirements:
        _locale: fr|en|de

germ_person:
    resource: "@GermBundle/Resources/config/routing/person.yml"
    prefix:   /{_locale}/person
    defaults:
        _locale: fr
    requirements:
        _locale: fr|en|de

germ_event:
    resource: "@GermBundle/Resources/config/routing/event.yml"
    prefix:   /{_locale}/event
    defaults:
        _locale: fr
    requirements:
        _locale: fr|en|de
