germ_homepage:
    path:     /
    defaults: { _controller: GermBundle:Main:index }

fos_user:
    prefix:   /access
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

germ_church:
    resource: "@GermBundle/Resources/config/routing/church.yml"
    prefix:   /church

germ_person:
    resource: "@GermBundle/Resources/config/routing/person.yml"
    prefix:   /person

germ_event:
    resource: "@GermBundle/Resources/config/routing/event.yml"
    prefix:   /event
