germ_homepage:
    path:     /
    defaults: { _controller: GermBundle:Main:index }

fos_user:
    prefix:   /access
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

germ_member_list:
    path:     /member/list
    defaults: { _controller: GermBundle:Member:list }

germ_member_edit:
    path:     /member/edit/{memberId}
    defaults: { _controller: GermBundle:Member:edit }
