germ_homepage:
    path:     /
    defaults: { _controller: GermBundle:Main:index }

fos_user:
    prefix:   /access
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

germ_person_list:
    path:     /person_{page}.{_format}
    defaults:
        _controller: GermBundle:Person:list
        _format: html
        page: 1
    requirements:
        _format:  html|csv|geojson

germ_person_filter:
    path:     /person/filter/{terms}/{roles}/{page}
    defaults:
        _format: html
        _controller: GermBundle:Person:list
        page: 1
        roles: all
        terms: all

germ_person_show:
    path:     /person/show/{personSlug}
    defaults: { _controller: GermBundle:Person:show }

germ_person_edit:
    path:     /person/edit/{personSlug}
    defaults: { _controller: GermBundle:Person:edit }

germ_person_remove:
    path:     /person/remove/{personSlug}
    defaults: { _controller: GermBundle:Person:remove }

germ_person_create:
    path:     /person/create
    defaults: { _controller: GermBundle:Person:create }

germ_person_account_disable:
    path:     /person/disable/{personSlug}
    defaults: { _controller: GermBundle:Person:accountActivation, enable: false }

germ_person_account_enable:
    path:     /person/enable/{personSlug}
    defaults: { _controller: GermBundle:Person:accountActivation, enable: true }

germ_event_list:
    path:     /event
    defaults: { _controller: GermBundle:Event:list }

germ_event_create:
    path:     /event/create
    defaults: { _controller: GermBundle:Event:create }

germ_event_edit:
    path:     /event/edit/{eventId}
    defaults: { _controller: GermBundle:Event:edit }

germ_event_show:
    path:     /event/{eventId}
    defaults: { _controller: GermBundle:Event:show }
    requirements:
        eventId:  \d

germ_event_remove:
    path:     /event/remove/{eventId}
    defaults: { _controller: GermBundle:Event:remove }
