

parameters:
    pomm_fos_user.user_model_class: GermBundle\Model\Germ\PersonSchema\AccountModel

services:
    GermBundle\Subscriber\PommPaginatorSubscriber:
        class: GermBundle\Subscriber\PommPaginatorSubscriber
        tags:
            - { name: knp_paginator.subscriber }

    GermBundle\Twig\StringifyExtension:
        class: GermBundle\Twig\StringifyExtension
        public: false
        tags:
            - { name: twig.extension }

    GermBundle\Twig\PersonExtension:
        class: GermBundle\Twig\PersonExtension
        autowire: true
        public: false
        tags:
            - { name: twig.extension }

    GermBundle\Twig\ChurchExtension:
        class: GermBundle\Twig\ChurchExtension
        autowire: true
        public: false
        tags:
            - { name: twig.extension }

    GermBundle\Twig\RouteExtension:
        class: GermBundle\Twig\RouteExtension
        public: false
        tags:
            - { name: twig.extension }

    GermBundle\Manager\EventManager:
        class: GermBundle\Manager\EventManager
        calls:
            - [setPomm, ['@pomm']]

    GermBundle\Filter\Church\Searcher:
        class: GermBundle\Filter\Church\Searcher
        autowire: true
        tags:
            - { name: "GermBundle\\Filter\\AbstractSearcher" }

    GermBundle\Filter\Church\CriteriaTerms:
        class: GermBundle\Filter\Church\CriteriaTerms
        autowire: true
        tags:
            - { name: "GermBundle\\Filter\\Church\\Searcher" }

    GermBundle\Filter\Person\Searcher:
        class: GermBundle\Filter\Person\Searcher
        autowire: true
        tags:
            - { name: "GermBundle\\Filter\\AbstractSearcher" }

    GermBundle\Filter\Person\CriteriaTerms:
        class: GermBundle\Filter\Person\CriteriaTerms
        autowire: true
        tags:
            - { name: "GermBundle\\Filter\\Person\\Searcher" }

    GermBundle\Filter\Person\CriteriaRoles:
        class: GermBundle\Filter\Person\CriteriaRoles
        autowire: true
        tags:
            - { name: "GermBundle\\Filter\\Person\\Searcher" }

    GermBundle\Person\RoleManager:
        class: GermBundle\Person\RoleManager
        calls:
            - [setConfig, ['%germ.roles%']]
        autowire: true

    GermBundle\Model\Germ\PersonSchema\PersonFinder:
        class: GermBundle\Model\Germ\PersonSchema\PersonFinder
        autowire: true

    GermBundle\Model\Germ\ChurchSchema\ChurchFinder:
        class: GermBundle\Model\Germ\ChurchSchema\ChurchFinder
        autowire: true

