

parameters:
    pomm_fos_user.user_model_class: GermBundle\Model\Germ\PersonSchema\AccountModel

services:
    germ.pomm.subscriber:
        class: GermBundle\Subscriber\PommSubscriber
        tags:
            - { name: knp_paginator.subscriber }

    germ.stringify_extension:
        class: GermBundle\Twig\StringifyExtension
        public: false
        tags:
            - { name: twig.extension }

    germ.event_manager:
        class: GermBundle\Manager\EventManager
        calls:
            - [setPomm, ['@pomm']]
