
parameters:
    pomm_fos_user.connection_name: 'germ'
    pomm_fos_user.user_model_class: GermBundle\Model\Germ\PublicSchema\UserModel

services:
#    germ.example:
#        class: GermBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
