

parameters:
    pomm_fos_user.user_model_class: GermBundle\Model\Germ\PersonSchema\AccountModel

services:
    GermBundle\Subscriber\PommSubscriber:
        class: GermBundle\Subscriber\PommSubscriber
        tags:
            - { name: knp_paginator.subscriber }

    GermBundle\Twig\StringifyExtension:
        class: GermBundle\Twig\StringifyExtension
        public: false
        tags:
            - { name: twig.extension }

    GermBundle\Twig\PersonExtension:
        class: GermBundle\Twig\PersonExtension
        autowire: true
        public: false
        tags:
            - { name: twig.extension }

    GermBundle\Twig\RouteExtension:
        class: GermBundle\Twig\RouteExtension
        public: false
        tags:
            - { name: twig.extension }

    GermBundle\Manager\EventManager:
        class: GermBundle\Manager\EventManager
        calls:
            - [setPomm, ['@pomm']]

    GermBundle\Person\Searcher:
        class: GermBundle\Person\Searcher
        autowire: true

    GermBundle\Person\SearchTerms:
        class: GermBundle\Person\SearchTerms
        autowire: true
        tags:
            - { name: "GermBundle\\Person\\AbstractSearchItem" }

    GermBundle\Person\SearchRoles:
        class: GermBundle\Person\SearchRoles
        autowire: true
        tags:
            - { name: "GermBundle\\Person\\AbstractSearchItem" }

    GermBundle\Person\RoleManager:
        class: GermBundle\Person\RoleManager
        calls:
            - [setConfig, ['%germ.roles%']]
        autowire: true
