

parameters:
    pomm_fos_user.user_model_class: GermBundle\Model\Germ\PersonSchema\AccountModel

services:
    GermBundle\Security\UserManager:
        class: GermBundle\Security\UserManager
        arguments:
            - "@fos_user.util.password_updater"
            - "@fos_user.util.canonical_fields_updater"
        calls:
            - [setPommModel, ["@pomm_fos_user_bundle.model_manager"]]

    fos_user.util.canonical_fields_updater:
        class: GermBundle\Security\CanonicalFieldsUpdater
        arguments:
            - "@fos_user.util.username_canonicalizer"
            - "@fos_user.util.email_canonicalizer"

#    security.role_hierarchy:
#        alias: Symfony\Component\Security\Core\Role\RoleHierarchy
#
#    pomm:
#        alias: PommProject\Foundation\Pomm

    GermBundle\EventSubscriber\PommPaginatorSubscriber:
        class: GermBundle\EventSubscriber\PommPaginatorSubscriber
        public: false
        tags:
            - { name: knp_paginator.subscriber }

    GermBundle\EventSubscriber\LocaleSubscriber:
        class: GermBundle\EventSubscriber\LocaleSubscriber
        public: false
        tags:
            - { name: kernel.event_subscriber }

    GermBundle\Twig\StringifyExtension:
        class: GermBundle\Twig\StringifyExtension
        public: false
        tags:
            - { name: twig.extension }

    GermBundle\Twig\PersonExtension:
        class: GermBundle\Twig\PersonExtension
        autowire: true
        public: false
        tags:
            - { name: twig.extension }

    GermBundle\Twig\CensusExtension:
        class: GermBundle\Twig\CensusExtension
        autowire: true
        public: false
        tags:
            - { name: twig.extension }

    GermBundle\Twig\ChurchExtension:
        class: GermBundle\Twig\ChurchExtension
        autowire: true
        public: false
        tags:
            - { name: twig.extension }

    GermBundle\Twig\RouteExtension:
        class: GermBundle\Twig\RouteExtension
        public: false
        tags:
            - { name: twig.extension }

    GermBundle\Manager\EventManager:
        class: GermBundle\Manager\EventManager
        calls:
            - [setPomm, ['@pomm']]

    GermBundle\Filter\Church\Searcher:
        class: GermBundle\Filter\Church\Searcher
        autowire: true
        tags:
            - { name: "GermBundle\\Filter\\AbstractSearcher" }

    GermBundle\Filter\Census\Searcher:
        class: GermBundle\Filter\Census\Searcher
        public: true
        autowire: true
        tags:
            - { name: "GermBundle\\Filter\\AbstractSearcher" }

    GermBundle\Model\Germ\Church\ChurchSaver:
        class: GermBundle\Model\Germ\Church\ChurchSaver
        autowire: true

    GermBundle\Filter\Church\CriteriaTerms:
        class: GermBundle\Filter\Church\CriteriaTerms
        autowire: true
        tags:
            - { name: "GermBundle\\Filter\\Church\\Searcher" }

    GermBundle\Filter\Person\Searcher:
        class: GermBundle\Filter\Person\Searcher
        autowire: true
        tags:
            - { name: "GermBundle\\Filter\\AbstractSearcher" }

    GermBundle\Filter\Person\CriteriaTerms:
        class: GermBundle\Filter\Person\CriteriaTerms
        autowire: true
        tags:
            - { name: "GermBundle\\Filter\\Person\\Searcher" }

    GermBundle\Filter\Person\CriteriaStatus:
        class: GermBundle\Filter\Person\CriteriaStatus
        autowire: true
        tags:
            - { name: "GermBundle\\Filter\\Person\\Searcher" }

    GermBundle\Filter\Person\CriteriaRoles:
        class: GermBundle\Filter\Person\CriteriaRoles
        autowire: true
        tags:
            - { name: "GermBundle\\Filter\\Person\\Searcher" }

    GermBundle\Filter\Person\CriteriaChurch:
        class: GermBundle\Filter\Person\CriteriaChurch
        autowire: true
        tags:
            - { name: "GermBundle\\Filter\\Person\\Searcher" }

    GermBundle\Filter\Person\CriteriaChurch2:
        class: GermBundle\Filter\Person\CriteriaChurch
        autowire: true
        tags:
            - { name: "GermBundle\\Filter\\Census\\Searcher" }

    GermBundle\Person\RoleManager:
        class: GermBundle\Person\RoleManager
        calls:
            - [setConfig, ['%germ.roles%']]
        autowire: true

    GermBundle\Person\Membership:
        class: GermBundle\Person\Membership
        autowire: true

    GermBundle\Model\Germ\Person\PersonFinder:
        public: true
        class: GermBundle\Model\Germ\Person\PersonFinder
        autowire: true

    GermBundle\Model\Germ\Church\ChurchFinder:
        public: true
        class: GermBundle\Model\Germ\Church\ChurchFinder
        autowire: true

    GermBundle\Model\Germ\Census\CensusFinder:
        public: true
        class: GermBundle\Model\Germ\Census\CensusFinder
        autowire: true

    GermBundle\Model\Germ\Census\CensusSaver:
        class: GermBundle\Model\Germ\Census\CensusSaver
        autowire: true

    GermBundle\Model\Germ\Person\PersonSaver:
        class: GermBundle\Model\Germ\Person\PersonSaver
        autowire: true

    GermBundle\Model\Germ\Person\AccountSaver:
        class: GermBundle\Model\Germ\Person\AccountSaver
        autowire: true

    GermBundle\Type\PersonType:
        class: GermBundle\Type\PersonType
        autowire: true
        tags:
            - { name: form.type }

    GermBundle\Type\AccountType:
        class: GermBundle\Type\AccountType
        autowire: true
        tags:
            - { name: form.type }

    GermBundle\Email\Mailer:
        class: GermBundle\Email\Mailer
        autowire: true
        calls:
            - [setEmailFrom, ["%germ.email.from%"]]

    GermBundle\Type\CensusType:
        class: GermBundle\Type\CensusType
        autowire: true
        tags:
            - { name: form.type }
