germ_census_list:
    path:     /censuses_{page}.{_format}
    controller: Germ\Legacy\Controller\CensusController::listAction
    defaults:
        _format: html
        page: 1
    requirements:
        _format:  html|csv

germ_census_filter:
    path:     /filter/{page}/{filters}
    controller: Germ\Legacy\Controller\CensusController::listAction
    defaults:
        _format: html
        page: 1
    requirements:
        filters: ".*"

germ_census_edit:
    path:     /edit/{censusId}
    controller: Germ\Legacy\Controller\CensusController::editAction

germ_census_remove:
    path:     /remove/{censusId}
    controller: Germ\Legacy\Controller\CensusController::removeAction

germ_census_create:
    path:     /create
    controller: Germ\Legacy\Controller\CensusController::createAction
