germ_church_list:
    path:     /churches_{page}.{_format}
    controller: Germ\Controller\ChurchController::listAction
    defaults:
        _format: html
        page: 1
    requirements:
        _format:  html|csv|geojson|json

germ_church_filter:
    path:     /filter/{page}/{filters}
    controller: Germ\Controller\ChurchController::listAction
    defaults:
        _format: html
        page: 1
    requirements:
        filters: ".*"

germ_church_edit:
    path:     /edit/{churchSlug}.{_format}
    controller: Germ\Controller\ChurchController::editAction
    defaults:
        _format: html
    requirements:
        _format:  html|json

germ_church_remove:
    path:     /remove/{churchSlug}
    controller: Germ\Controller\ChurchController::removeAction

germ_church_create:
    path:     /create
    controller: Germ\Controller\ChurchController::createAction
