germ_event_list:
    path:     /
    controller: Germ\Controller\EventController::list

germ_event_create:
    path:     /create
    controller: Germ\Controller\ChurchController::create

germ_event_edit:
    path:     /edit/{eventId}
    controller: Germ\Controller\ChurchController::edit

germ_event_show:
    path:     /{eventId}
    controller: Germ\Controller\ChurchController::show
    requirements:
        eventId:  \d

germ_event_remove:
    path:     /sremove/{eventId}
    controller: Germ\Controller\ChurchController::remove
