germ_event_list:
    path:     /
    controller: Germ\Controller\EventController::listAction

germ_event_create:
    path:     /create
    controller: Germ\Controller\ChurchController::createAction

germ_event_edit:
    path:     /edit/{eventId}
    controller: Germ\Controller\ChurchController::editAction

germ_event_show:
    path:     /{eventId}
    controller: Germ\Controller\ChurchController::showAction
    requirements:
        eventId:  \d

germ_event_remove:
    path:     /sremove/{eventId}
    controller: Germ\Controller\ChurchController::removeAction
