germ_person_filter:
    path:     /filter/{page}/{filters}
    controller: Germ\Controller\PersonController::list
    defaults:
        _format: html
        page: 1
    requirements:
        filters: ".*"

germ_person_show:
    path:     /show/{personSlug}
    controller: Germ\Controller\PersonController::show

germ_person_edit:
    path:     /edit/{personSlug}
    controller: Germ\Controller\PersonController::edit

germ_person_edit_myself:
    path:     /edit_myself
    controller: Germ\Controller\PersonController::edit

germ_person_remove:
    path:     /remove/{personSlug}
    controller: Germ\Controller\PersonController::remove

germ_person_recreate:
    path:     /recreate/{personSlug}
    controller: Germ\Controller\PersonController::recreate

germ_person_create:
    path:     /create
    controller: Germ\Controller\PersonController::create

germ_person_account_disable:
    path:     /disable/{personSlug}
    controller: Germ\Controller\PersonController::accountActivation
    defaults: { enable: false }

germ_person_account_enable:
    path:     /enable/{personSlug}
    controller: Germ\Controller\PersonController::accountActivation
    defaults: { enable: true }

germ_person_list:
    path:     /{page}.{_format}
    controller: Germ\Controller\PersonController::list
    defaults:
        _format: html
        page: 1
    requirements:
        _format:  html|csv|geojson

