germ_person_filter:
    path:     /filter/{page}/{filters}
    defaults:
        _format: html
        _controller: Germ:Person:list
        page: 1
    requirements:
        filters: ".*"

germ_person_show:
    path:     /show/{personSlug}
    defaults: { _controller: Germ:Person:show }

germ_person_edit:
    path:     /edit/{personSlug}
    defaults: { _controller: Germ:Person:edit }

germ_person_edit_myself:
    path:     /edit_myself
    defaults: { _controller: Germ:Person:edit }

germ_person_remove:
    path:     /remove/{personSlug}
    defaults: { _controller: Germ:Person:remove }

germ_person_recreate:
    path:     /recreate/{personSlug}
    defaults: { _controller: Germ:Person:recreate  }

germ_person_create:
    path:     /create
    defaults: { _controller: Germ:Person:create }

germ_person_account_disable:
    path:     /disable/{personSlug}
    defaults: { _controller: Germ:Person:accountActivation, enable: false }

germ_person_account_enable:
    path:     /enable/{personSlug}
    defaults: { _controller: Germ:Person:accountActivation, enable: true }

germ_person_list:
    path:     /{page}.{_format}
    defaults:
        _controller: Germ:Person:list
        _format: html
        page: 1
    requirements:
        _format:  html|csv|geojson

