germ_person_filter:
    path:     /filter/{page}/{filters}
    controller: Germ\Legacy\Controller\PersonController::listAction
    defaults:
        _format: html
        page: 1
    requirements:
        filters: ".*"

germ_person_show:
    path:     /show/{personSlug}
    controller: Germ\Legacy\Controller\PersonController::showAction

germ_person_edit:
    path:     /edit/{personSlug}
    controller: Germ\Legacy\Controller\PersonController::editAction

germ_person_edit_myself:
    path:     /edit_myself
    controller: Germ\Legacy\Controller\PersonController::editAction

germ_person_remove:
    path:     /remove/{personSlug}
    controller: Germ\Legacy\Controller\PersonController::removeAction

germ_person_recreate:
    path:     /recreate/{personSlug}
    controller: Germ\Legacy\Controller\PersonController::recreateAction

germ_person_create:
    path:     /create
    controller: Germ\Legacy\Controller\PersonController::createAction

germ_person_account_disable:
    path:     /disable/{personSlug}
    controller: Germ\Legacy\Controller\PersonController::accountActivationAction
    defaults: { enable: false }

germ_person_account_enable:
    path:     /enable/{personSlug}
    controller: Germ\Legacy\Controller\PersonController::accountActivationAction
    defaults: { enable: true }

germ_person_list:
    path:     /{page}.{_format}
    controller: Germ\Legacy\Controller\PersonController::listAction
    defaults:
        _format: html
        page: 1
    requirements:
        _format:  html|csv|geojson

