_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error

_pomm:
    resource: "@PommBundle/Resources/config/routing.yml"
    prefix:   /_pomm

_debug:
    resource: "../../src/Resources/config/routing_dev.yml"
    prefix:   /_debug
