<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace GermBundle\Model\Germ\EventSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Event
 *
 * Structure class for relation event.event.
 *
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Event extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('event.event')
            ->setPrimaryKey(['id_event_event'])
            ->addField('id_event_event', 'uuid')
            ->addField('type_id', 'uuid')
            ->addField('location_id', 'uuid')
            ->addField('name', 'varchar')
            ->addField('date_from', 'timestamp')
            ->addField('duration', 'interval')
            ->addField('is_deleted', 'bool')
            ->addField('description', 'text')
            ;
    }
}
