<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace Germ\Model\Germ\EventSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * EventType
 *
 * Structure class for relation event.event_type.
 *
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class EventType extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('event.event_type')
            ->setPrimaryKey(['id_event_event_type'])
            ->addField('id_event_event_type', 'uuid')
            ->addField('name', 'varchar')
            ->addField('recurence', 'varchar')
            ->addField('event_layout', 'json')
            ;
    }
}
