security:

    role_hierarchy:
        ROLE_PERSON_READ:  ROLE_PERSON_SEE, ROLE_PERSON_LIST
        ROLE_PERSON_WRITE: ROLE_PERSON_DELETE, ROLE_PERSON_CREATE, ROLE_PERSON_EDIT
        ROLE_EVERT_READ:   ROLE_EVENT_SEE, ROLE_EVENT_LIST
        ROLE_EVENT_WRITE:  ROLE_EVENT_DELETE, ROLE_EVENT_CREATE, ROLE_EVENT_EDIT
        ROLE_SECRETARY:    ROLE_PERSON_READ, ROLE_PERSON_WRITE, ROLE_EVENT_WRITE, ROLE_EVENT_READ
        ROLE_ELDER:        ROLE_PERSON_READ, ROLE_EVENT_READ
        ROLE_PASTEUR:      ROLE_PERSON_READ, ROLE_EVENT_READ
        ROLE_ADMIN:        ROLE_ELDER, ROLE_SECRETARY, ROLE_CHURCH_LIST
        ROLE_DEACON:       ROLE_FIRST_DEACON
        ROLE_DEACONESS:    ROLE_FIRST_DEACONESS
        ROLE_DIACONATE:    ROLE_DEACON, ROLE_DEACONESS

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt|debug)|css|images|js)/
            security: false

        main:
            anonymous: true
            form_login:
                login_path: /access/login
                check_path: /access/login_check
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /access/logout
                target: /
            remember_me:
                secret:   "%secret%"
                lifetime: 604800 # 1 week in seconds
                path: /

    access_control:
        - { path: ^/access/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/person/create, roles: ROLE_PERSON_CREATE }
        - { path: ^/person/delete, roles: ROLE_PERSON_DELETE }
        - { path: ^/person/edit, roles: ROLE_PERSON_DELETE }
        - { path: ^/person, roles: ROLE_PERSON_SEE }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
