security:

    role_hierarchy:
        ROLE_SECRETAIRE:    ROLE_DELETE_MEMBER, ROLE_CREATE_MEMBER, ROLE_SEE_MEMBER
        ROLE_ANCIEN:        ROLE_SEE_MEMBER
        ROLE_PASTEUR:       ROLE_SEE_MEMBER
        ROLE_ADMIN:         ROLE_ANCIEN, ROLE_SECRETAIRE

    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        chain_provider:
            chain:
                providers: [in_memory, fos_userbundle]
        in_memory:
            memory:
                users:
                    admin:
                        password: germ
                        roles: 'ROLE_ADMIN'
                    secretaire:
                        password: germ
                        roles: 'ROLE_SECRETAIRE'
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt|debug)|css|images|js)/
            security: false

        main:
            anonymous: true
            form_login:
                login_path: /access/login
                check_path: /access/login_check
                provider: chain_provider
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /access/logout
                target: /
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path: /

    access_control:
        - { path: ^/access/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/member/create, roles: ROLE_CREATE_MEMBER }
        - { path: ^/member/delete, roles: ROLE_DELETE_MEMBER }
        - { path: ^/member, roles: ROLE_SEE_MEMBER }
