security:

    role_hierarchy:
        ROLE_SECRETAIRE:    ROLE_DELETE_MEMBER, ROLE_CREATE_MEMBER, ROLE_SEE_MEMBER
        ROLE_ANCIEN:        ROLE_SEE_MEMBER
        ROLE_PASTEUR:       ROLE_SEE_MEMBER
        ROLE_ADMIN:         ROLE_ANCIEN, ROLE_SECRETAIRE

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt|debug)|css|images|js)/
            security: false

        main:
            anonymous: true
            form_login:
                login_path: /access/login
                check_path: /access/login_check
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /access/logout
                target: /
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path: /

    access_control:
        - { path: ^/access/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/person/create, roles: ROLE_CREATE_MEMBER }
        - { path: ^/person/delete, roles: ROLE_DELETE_MEMBER }
        - { path: ^/person/edit, roles: ROLE_DELETE_MEMBER }
        - { path: ^/person, roles: ROLE_SEE_MEMBER }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
