security:

    role_hierarchy:
        ROLE_SECRETAIRE:    ROLE_DELETE_MEMBER, ROLE_CREATE_MEMBER, ROLE_SEE_MEMBER
        ROLE_ANCIEN:        ROLE_SEE_MEMBER
        ROLE_PASTEUR:       ROLE_SEE_MEMBER
        ROLE_ADMIN:         ROLE_ANCIEN, ROLE_SECRETAIRE

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: germ
                        roles: 'ROLE_ADMIN'
                    secretaire:
                        password: germ
                        roles: 'ROLE_SECRETAIRE'
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login
            logout:
                path: /logout
                target: /
#                success_handler: logout_listener
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/member/create, roles: ROLE_CREATE_MEMBER }
        - { path: ^/member/delete, roles: ROLE_DELETE_MEMBER }
        - { path: ^/member, roles: ROLE_SEE_MEMBER }
