<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace GermBundle\Model\Germ\EventSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Docket
 *
 * Structure class for relation event.docket.
 *
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Docket extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('event.docket')
            ->setPrimaryKey(['id_event_docket'])
            ->addField('id_event_docket', 'uuid')
            ->addField('name', 'varchar')
            ->addField('role', 'varchar[]')
            ->addField('event_type_id', 'uuid')
            ;
    }
}
