version: '3'

services:
  germ-postgres:
    image: postgres:9.6
    container_name: germ-postgres
    environment:
      POSTGRES_PASSWORD: SuP3RP455w0Rd
      POSTGRES_USER: germ
    ports:
      - 5432:5432

  germ-webserver:
    image: phpdockerio/nginx:latest
    container_name: germ-webserver
    volumes:
      - ..:/var/www/germ:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../var/log/nginx:/var/log/nginx
      - "./app/letsencrypt/www:/var/www/letsencrypt"
      - "./app/letsencrypt/etc:/etc/letsencrypt"
    ports:
      - "8095:80"
    links:
      - germ-php-fpm
    expose:
      - 8095

  germ-php-fpm:
    build:
      context: ./php-fpm
    container_name: germ-php-fpm
    ports:
      - 9000:9000
    volumes:
      - ..:/var/www/germ
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini:ro
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/cli/conf.d/99-overrides.ini:ro
    links:
      - germ-postgres

  germ-cerbot:
    image: certbot/certbot
    volumes:
      - "./app/letsencrypt/www:/var/www/letsencrypt"
      - "./app/letsencrypt/etc:/etc/letsencrypt"

  germ-nodejs:
    image: node:8.12.0-alpine
    container_name: germ-nodejs
    volumes:
      - ..:/var/www/germ


# FOR DNS problems, see here : https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/
