

parameters:
    pomm_fos_user.user_model_class: Germ\Legacy\Model\Germ\PersonSchema\AccountModel

services:

    # Globals

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    Germ\Legacy\:
        resource: '../src/Germ/Legacy/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    Germ\Legacy\Controller\:
        resource: '../src/Germ/Legacy/Controller'
        tags: ['controller.service_arguments']

    _instanceof:
#        "\\Twig_Extension":
#            tags:
#                - { name: twig.extension }

        "Germ\\Legacy\\Filter\\AbstractSearcher":
            tags:
                - { name: Germ\Legacy\\Filter\\AbstractSearcher }

#        "Symfony\\Component\\Form\\AbstractType":
#            tags:
#                - { name: form.type }

    # Alias on interfaces

    FOS\UserBundle\Util\CanonicalFieldsUpdater:
        alias: fos_user.util.canonical_fields_updater

    FOS\UserBundle\Util\PasswordUpdaterInterface:
        alias: fos_user.util.password_updater

    Symfony\Component\Security\Core\Role\RoleHierarchyInterface:
        alias: security.role_hierarchy

    # Specific

    Germ\Legacy\Security\UserManager:
        calls:
            - [setPommModel, ["@pomm_fos_user_bundle.model_manager"]]

    fos_user.util.canonical_fields_updater:
        class: Germ\Legacy\Security\CanonicalFieldsUpdater
        arguments:
            - "@fos_user.util.username_canonicalizer"
            - "@fos_user.util.email_canonicalizer"

    Germ\Legacy\Person\RoleManager:
        calls:
            - [setConfig, ['%germ.roles%']]

    Germ\Legacy\Email\Mailer:
        calls:
            - [setEmailFrom, ["%germ.email.from%"]]

    # events subscribers

    Germ\Legacy\EventSubscriber\PommPaginatorSubscriber:
        tags:
            - { name: knp_paginator.subscriber }

    Germ\Legacy\EventSubscriber\LocaleSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    Germ\Legacy\EventSubscriber\HttpHeaderSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    # search criterias

    Germ\Legacy\Filter\Church\Searcher:
        tags:
            - { name: "Germ\\Legacy\\Filter\\AbstractSearcher" }

    Germ\Legacy\Filter\Church\CriteriaTerms:
        tags:
            - { name: "Germ\\Legacy\\Filter\\Church\\Searcher" }

    Germ\Legacy\Filter\Person\Searcher:
        tags:
            - { name: "Germ\\Legacy\\Filter\\AbstractSearcher" }

    Germ\Legacy\Filter\Person\CriteriaTerms:
        tags:
            - { name: "Germ\\Legacy\\Filter\\Person\\Searcher" }

    Germ\Legacy\Filter\Person\CriteriaStatus:
        tags:
            - { name: "Germ\\Legacy\\Filter\\Person\\Searcher" }

    Germ\Legacy\Filter\Person\CriteriaRoles:
        tags:
            - { name: "Germ\\Legacy\\Filter\\Person\\Searcher" }

    Germ\Legacy\Filter\Person\CriteriaChurch:
        tags:
            - { name: "Germ\\Legacy\\Filter\\Person\\Searcher" }

    Germ\Legacy\Filter\Census\Searcher:
        tags:
            - { name: "Germ\\Legacy\\Filter\\AbstractSearcher" }

    Germ\Legacy\Filter\Person\CriteriaChurch2:
        class: Germ\Legacy\Filter\Person\CriteriaChurch
        tags:
            - { name: "Germ\\Legacy\\Filter\\Census\\Searcher" }
