<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace Germ\Legacy\Model\Germ\EventSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Assignation
 *
 * Structure class for relation event.assignation.
 *
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Assignation extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('event.assignation')
            ->setPrimaryKey(['person_id','docket_id','event_id'])
            ->addField('person_id', 'uuid')
            ->addField('docket_id', 'uuid')
            ->addField('event_id', 'uuid')
            ->addField('details', 'json')
            ;
    }
}
