<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace Germ\Model\Germ\CommunicationSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Sms
 *
 * Structure class for relation communication.sms.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Sms extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('communication.sms')
            ->setPrimaryKey(['id_communication_sms'])
            ->addField('id_communication_sms', 'uuid')
            ->addField('date', 'timestamp')
            ->addField('content', 'varchar')
            ->addField('status', 'varchar')
            ->addField('church_id', 'uuid')
            ;
    }
}
