<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace GermBundle\Model\Germ\ChurchSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Census
 *
 * Structure class for relation church.census.
 *
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Census extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('church.census')
            ->setPrimaryKey(['id_church_census'])
            ->addField('id_church_census', 'uuid')
            ->addField('date', 'timestamp')
            ->addField('count', 'int4')
            ->addField('church_id', 'uuid')
            ;
    }
}
