germ_church_list:
    path:     /churches_{page}.{_format}
    defaults:
        _controller: GermBundle:Church:list
        _format: html
        page: 1
    requirements:
        _format:  html|csv|geojson

germ_church_filter:
    path:     /filter/{page}/{filters}
    defaults:
        _format: html
        _controller: GermBundle:Church:list
        page: 1
    requirements:
        filters: ".*"

germ_church_edit:
    path:     /edit/{churchSlug}
    defaults: { _controller: GermBundle:Church:edit }

germ_church_remove:
    path:     /remove/{churchSlug}
    defaults: { _controller: GermBundle:Church:remove }

germ_church_create:
    path:     /create
    defaults: { _controller: GermBundle:Church:create }
